import {UniverseSpec} from '../dimensions';

export const firewallSpec: UniverseSpec = {
  types: [
    {
      name: 'ip address',
      key: 'ip',
      parser: 'ip',
      formatter: 'ip',
      domain: '0.0.0.0-255.255.255.255',
      values: [
        {symbol: 'internet', range: '0.0.0.0-255.255.255.255'},
        {symbol: 'localhost', range: '127.0.0.1'},
        {symbol: 'loopback', range: '127.0.0.0/8'},
      ],
    },
    {
      name: 'port',
      key: 'port',
      parser: 'default',
      formatter: 'default',
      domain: '00-0xffff',
      values: [
        {symbol: 'FTP', range: '21'},
        {symbol: 'SSH', range: '22'},
        {symbol: 'telnet', range: '23'},
        {symbol: 'SMTP', range: '25'},
        {symbol: 'time', range: '37'},
        {symbol: 'whois', range: '43'},
        {symbol: 'DNS', range: '53'},
        {symbol: 'gopher', range: '70'},
        {symbol: 'finger', range: '79'},
        {symbol: 'HTTP', range: '80, 443'},
        {symbol: 'MSSQL', range: '1433,1434'},
        {symbol: 'ephemeral', range: '49152–65535'},
      ],
    },
    {
      name: 'protocol',
      key: 'protocol',
      parser: 'default',
      formatter: 'default',
      domain: '00-0xff',
      values: [
        {symbol: 'HOPOPT', range: '0'},
        {symbol: 'ICMP', range: '1'},
        {symbol: 'IGMP', range: '2'},
        {symbol: 'GGP', range: '3'},
        {symbol: 'IPv4', range: '4'},
        {symbol: 'ST', range: '5'},
        {symbol: 'TCP', range: '6'},
        {symbol: 'CBT', range: '7'},
        {symbol: 'EGP', range: '8'},
        {symbol: 'IGP', range: '9'},
        {symbol: 'BBN_RCC_MON', range: '10'},
        {symbol: 'NVP_II', range: '11'},
        {symbol: 'PUP', range: '12'},
        {symbol: 'EMCON', range: '14'},
        {symbol: 'XNET', range: '15'},
        {symbol: 'CHAOS', range: '16'},
        {symbol: 'UDP', range: '17'},
        {symbol: 'MUX', range: '18'},
        {symbol: 'DCN_MEAS', range: '19'},
        {symbol: 'HMP', range: '20'},
        {symbol: 'PRM', range: '21'},
        {symbol: 'XNS_IDP', range: '22'},
        {symbol: 'TRUNK_1', range: '23'},
        {symbol: 'TRUNK_2', range: '24'},
        {symbol: 'LEAF_1', range: '25'},
        {symbol: 'LEAF_2', range: '26'},
        {symbol: 'RDP', range: '27'},
        {symbol: 'IRTP', range: '28'},
        {symbol: 'ISO_TP4', range: '29'},
        {symbol: 'NETBLT', range: '30'},
        {symbol: 'MFE_NSP', range: '31'},
        {symbol: 'MERIT_INP', range: '32'},
        {symbol: 'DCCP', range: '33'},
        {symbol: '3PC', range: '34'},
        {symbol: 'IDPR', range: '35'},
        {symbol: 'XTP', range: '36'},
        {symbol: 'DDP', range: '37'},
        {symbol: 'IDPR_CMTP', range: '38'},
        {symbol: 'TP++', range: '39'},
        {symbol: 'IL', range: '40'},
        {symbol: 'IPv6', range: '41'},
        {symbol: 'SDRP', range: '42'},
        {symbol: 'IPv6_Route', range: '43'},
        {symbol: 'IPv6_Frag', range: '44'},
        {symbol: 'IDRP', range: '45'},
        {symbol: 'RSVP', range: '46'},
        {symbol: 'GRE', range: '47'},
        {symbol: 'DSR', range: '48'},
        {symbol: 'BNA', range: '49'},
        {symbol: 'ESP', range: '50'},
        {symbol: 'AH', range: '51'},
        {symbol: 'I_NLSP', range: '52'},
        {symbol: 'NARP', range: '54'},
        {symbol: 'MOBILE', range: '55'},
        {symbol: 'TLSP', range: '56'},
        {symbol: 'SKIP', range: '57'},
        {symbol: 'IPv6_ICMP', range: '58'},
        {symbol: 'IPv6_NoNxt', range: '59'},
        {symbol: 'IPv6_Opts', range: '60'},
        {symbol: 'CFTP', range: '62'},
        {symbol: 'SAT_EXPAK', range: '64'},
        {symbol: 'KRYPTOLAN', range: '65'},
        {symbol: 'RVD', range: '66'},
        {symbol: 'IPPC', range: '67'},
        {symbol: 'SAT_MON', range: '69'},
        {symbol: 'VISA', range: '70'},
        {symbol: 'IPCV', range: '71'},
        {symbol: 'CPNX', range: '72'},
        {symbol: 'CPHB', range: '73'},
        {symbol: 'WSN', range: '74'},
        {symbol: 'PVP', range: '75'},
        {symbol: 'BR_SAT_MON', range: '76'},
        {symbol: 'SUN_ND', range: '77'},
        {symbol: 'WB_MON', range: '78'},
        {symbol: 'WB_EXPAK', range: '79'},
        {symbol: 'ISO_IP', range: '80'},
        {symbol: 'VMTP', range: '81'},
        {symbol: 'SECURE_VMTP', range: '82'},
        {symbol: 'VINES', range: '83'},
        {symbol: 'TTP', range: '84'},
        {symbol: 'IPTM', range: '84'},
        {symbol: 'NSFNET_IGP', range: '85'},
        {symbol: 'DGP', range: '86'},
        {symbol: 'TCF', range: '87'},
        {symbol: 'EIGRP', range: '88'},
        {symbol: 'OSPFIGP', range: '89'},
        {symbol: 'Sprite_RPC', range: '90'},
        {symbol: 'LARP', range: '91'},
        {symbol: 'MTP', range: '92'},
        {symbol: 'AX.25', range: '93'},
        {symbol: 'IPIP', range: '94'},
        {symbol: 'SCC_SP', range: '96'},
        {symbol: 'ETHERIP', range: '97'},
        {symbol: 'ENCAP', range: '98'},
        {symbol: 'GMTP', range: '100'},
        {symbol: 'IFMP', range: '101'},
        {symbol: 'PNNI', range: '102'},
        {symbol: 'PIM', range: '103'},
        {symbol: 'ARIS', range: '104'},
        {symbol: 'SCPS', range: '105'},
        {symbol: 'QNX', range: '106'},
        {symbol: 'A/N', range: '107'},
        {symbol: 'IPComp', range: '108'},
        {symbol: 'SNP', range: '109'},
        {symbol: 'Compaq_Peer', range: '110'},
        {symbol: 'IPX_in_IP', range: '111'},
        {symbol: 'VRRP', range: '112'},
        {symbol: 'PGM', range: '113'},
        {symbol: 'L2TP', range: '115'},
        {symbol: 'DDX', range: '116'},
        {symbol: 'IATP', range: '117'},
        {symbol: 'STP', range: '118'},
        {symbol: 'SRP', range: '119'},
        {symbol: 'UTI', range: '120'},
        {symbol: 'SMP', range: '121'},
        {symbol: 'PTP', range: '123'},
        {symbol: 'FIRE', range: '125'},
        {symbol: 'CRTP', range: '126'},
        {symbol: 'CRUDP', range: '127'},
        {symbol: 'SSCOPMCE', range: '128'},
        {symbol: 'IPLT', range: '129'},
        {symbol: 'SPS', range: '130'},
        {symbol: 'PIPE', range: '131'},
        {symbol: 'SCTP', range: '132'},
        {symbol: 'FC', range: '133'},
        {symbol: 'RSVP_E2E_IGNORE', range: '134'},
        {symbol: 'UDPLite', range: '136'},
        {symbol: 'MPLS_in_IP', range: '137'},
        {symbol: 'manet', range: '138'},
        {symbol: 'HIP', range: '139'},
        {symbol: 'Shim6', range: '140'},
        {symbol: 'WESP', range: '141'},
        {symbol: 'ROHC', range: '142'},
        {symbol: 'Ethernet', range: '143'},
        {symbol: 'Reserved', range: '255'},
      ],
    },
  ],
  dimensions: [
    {
      name: 'source ip',
      key: 'sourceIp',
      type: 'ip',
    },
    {
      name: 'source port',
      key: 'sourcePort',
      type: 'port',
    },
    {
      name: 'destination ip',
      key: 'destinationIp',
      type: 'ip',
    },
    {
      name: 'destination port',
      key: 'destinationPort',
      type: 'port',
    },
    {
      name: 'protocol',
      key: 'protocol',
      type: 'protocol',
    },
  ],
};
