// Data from https://www.iana.org/assignments/protocol-numbers/protocol-numbers-1.csv
// Converted to CSV with https://www.npmjs.com/package/csvtojson
export const ianaData = [
  {
    Decimal: '0',
    Keyword: 'HOPOPT',
    Protocol: 'IPv6 Hop-by-Hop Option',
    'IPv6 Extension Header': 'Y',
    Reference: '[RFC8200]',
  },
  {
    Decimal: '1',
    Keyword: 'ICMP',
    Protocol: 'Internet Control Message',
    'IPv6 Extension Header': '',
    Reference: '[RFC792]',
  },
  {
    Decimal: '2',
    Keyword: 'IGMP',
    Protocol: 'Internet Group Management',
    'IPv6 Extension Header': '',
    Reference: '[RFC1112]',
  },
  {
    Decimal: '3',
    Keyword: 'GGP',
    Protocol: 'Gateway-to-Gateway',
    'IPv6 Extension Header': '',
    Reference: '[RFC823]',
  },
  {
    Decimal: '4',
    Keyword: 'IPv4',
    Protocol: 'IPv4 encapsulation',
    'IPv6 Extension Header': '',
    Reference: '[RFC2003]',
  },
  {
    Decimal: '5',
    Keyword: 'ST',
    Protocol: 'Stream',
    'IPv6 Extension Header': '',
    Reference: '[RFC1190][RFC1819]',
  },
  {
    Decimal: '6',
    Keyword: 'TCP',
    Protocol: 'Transmission Control',
    'IPv6 Extension Header': '',
    Reference: '[RFC793]',
  },
  {
    Decimal: '7',
    Keyword: 'CBT',
    Protocol: 'CBT',
    'IPv6 Extension Header': '',
    Reference: '[Tony_Ballardie]',
  },
  {
    Decimal: '8',
    Keyword: 'EGP',
    Protocol: 'Exterior Gateway Protocol',
    'IPv6 Extension Header': '',
    Reference: '[RFC888][David_Mills]',
  },
  {
    Decimal: '9',
    Keyword: 'IGP',
    Protocol:
      'any private interior gateway             \r\n(used by Cisco for their IGRP)',
    'IPv6 Extension Header': '',
    Reference: '[Internet_Assigned_Numbers_Authority]',
  },
  {
    Decimal: '10',
    Keyword: 'BBN-RCC-MON',
    Protocol: 'BBN RCC Monitoring',
    'IPv6 Extension Header': '',
    Reference: '[Steve_Chipman]',
  },
  {
    Decimal: '11',
    Keyword: 'NVP-II',
    Protocol: 'Network Voice Protocol',
    'IPv6 Extension Header': '',
    Reference: '[RFC741][Steve_Casner]',
  },
  {
    Decimal: '12',
    Keyword: 'PUP',
    Protocol: 'PUP',
    'IPv6 Extension Header': '',
    Reference:
      '[Boggs, D., J. Shoch, E. Taft, and R. Metcalfe, "PUP: An\r\nInternetwork Architecture", XEROX Palo Alto Research Center,\r\nCSL-79-10, July 1979; also in IEEE Transactions on\r\nCommunication, Volume COM-28, Number 4, April 1980.][[XEROX]]',
  },
  {
    Decimal: '13',
    Keyword: 'ARGUS (deprecated)',
    Protocol: 'ARGUS',
    'IPv6 Extension Header': '',
    Reference: '[Robert_W_Scheifler]',
  },
  {
    Decimal: '14',
    Keyword: 'EMCON',
    Protocol: 'EMCON',
    'IPv6 Extension Header': '',
    Reference: '[<mystery contact>]',
  },
  {
    Decimal: '15',
    Keyword: 'XNET',
    Protocol: 'Cross Net Debugger',
    'IPv6 Extension Header': '',
    Reference:
      '[Haverty, J., "XNET Formats for Internet Protocol Version 4",\r\nIEN 158, October 1980.][Jack_Haverty]',
  },
  {
    Decimal: '16',
    Keyword: 'CHAOS',
    Protocol: 'Chaos',
    'IPv6 Extension Header': '',
    Reference: '[J_Noel_Chiappa]',
  },
  {
    Decimal: '17',
    Keyword: 'UDP',
    Protocol: 'User Datagram',
    'IPv6 Extension Header': '',
    Reference: '[RFC768][Jon_Postel]',
  },
  {
    Decimal: '18',
    Keyword: 'MUX',
    Protocol: 'Multiplexing',
    'IPv6 Extension Header': '',
    Reference:
      '[Cohen, D. and J. Postel, "Multiplexing Protocol", IEN 90,\r\nUSC/Information Sciences Institute, May 1979.][Jon_Postel]',
  },
  {
    Decimal: '19',
    Keyword: 'DCN-MEAS',
    Protocol: 'DCN Measurement Subsystems',
    'IPv6 Extension Header': '',
    Reference: '[David_Mills]',
  },
  {
    Decimal: '20',
    Keyword: 'HMP',
    Protocol: 'Host Monitoring',
    'IPv6 Extension Header': '',
    Reference: '[RFC869][Bob_Hinden]',
  },
  {
    Decimal: '21',
    Keyword: 'PRM',
    Protocol: 'Packet Radio Measurement',
    'IPv6 Extension Header': '',
    Reference: '[Zaw_Sing_Su]',
  },
  {
    Decimal: '22',
    Keyword: 'XNS-IDP',
    Protocol: 'XEROX NS IDP',
    'IPv6 Extension Header': '',
    Reference:
      '["The Ethernet, A Local Area Network: Data Link Layer and\r\nPhysical Layer Specification", AA-K759B-TK, Digital\r\nEquipment Corporation, Maynard, MA.  Also as: "The\r\nEthernet - A Local Area Network", Version 1.0, Digital\r\nEquipment Corporation, Intel Corporation, Xerox\r\nCorporation, September 1980.  And: "The Ethernet, A Local\r\nArea Network: Data Link Layer and Physical Layer\r\nSpecifications", Digital, Intel and Xerox, November 1982.\r\nAnd: XEROX, "The Ethernet, A Local Area Network: Data Link\r\nLayer and Physical Layer Specification", X3T51/80-50,\r\nXerox Corporation, Stamford, CT., October 1980.][[XEROX]]',
  },
  {
    Decimal: '23',
    Keyword: 'TRUNK-1',
    Protocol: 'Trunk-1',
    'IPv6 Extension Header': '',
    Reference: '[Barry_Boehm]',
  },
  {
    Decimal: '24',
    Keyword: 'TRUNK-2',
    Protocol: 'Trunk-2',
    'IPv6 Extension Header': '',
    Reference: '[Barry_Boehm]',
  },
  {
    Decimal: '25',
    Keyword: 'LEAF-1',
    Protocol: 'Leaf-1',
    'IPv6 Extension Header': '',
    Reference: '[Barry_Boehm]',
  },
  {
    Decimal: '26',
    Keyword: 'LEAF-2',
    Protocol: 'Leaf-2',
    'IPv6 Extension Header': '',
    Reference: '[Barry_Boehm]',
  },
  {
    Decimal: '27',
    Keyword: 'RDP',
    Protocol: 'Reliable Data Protocol',
    'IPv6 Extension Header': '',
    Reference: '[RFC908][Bob_Hinden]',
  },
  {
    Decimal: '28',
    Keyword: 'IRTP',
    Protocol: 'Internet Reliable Transaction',
    'IPv6 Extension Header': '',
    Reference: '[RFC938][Trudy_Miller]',
  },
  {
    Decimal: '29',
    Keyword: 'ISO-TP4',
    Protocol: 'ISO Transport Protocol Class 4',
    'IPv6 Extension Header': '',
    Reference: '[RFC905][<mystery contact>]',
  },
  {
    Decimal: '30',
    Keyword: 'NETBLT',
    Protocol: 'Bulk Data Transfer Protocol',
    'IPv6 Extension Header': '',
    Reference: '[RFC969][David_Clark]',
  },
  {
    Decimal: '31',
    Keyword: 'MFE-NSP',
    Protocol: 'MFE Network Services Protocol',
    'IPv6 Extension Header': '',
    Reference:
      '[Shuttleworth, B., "A Documentary of MFENet, a National\r\nComputer Network", UCRL-52317, Lawrence Livermore Labs,\r\nLivermore, California, June 1977.][Barry_Howard]',
  },
  {
    Decimal: '32',
    Keyword: 'MERIT-INP',
    Protocol: 'MERIT Internodal Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Hans_Werner_Braun]',
  },
  {
    Decimal: '33',
    Keyword: 'DCCP',
    Protocol: 'Datagram Congestion Control Protocol',
    'IPv6 Extension Header': '',
    Reference: '[RFC4340]',
  },
  {
    Decimal: '34',
    Keyword: '3PC',
    Protocol: 'Third Party Connect Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Stuart_A_Friedberg]',
  },
  {
    Decimal: '35',
    Keyword: 'IDPR',
    Protocol: 'Inter-Domain Policy Routing Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Martha_Steenstrup]',
  },
  {
    Decimal: '36',
    Keyword: 'XTP',
    Protocol: 'XTP',
    'IPv6 Extension Header': '',
    Reference: '[Greg_Chesson]',
  },
  {
    Decimal: '37',
    Keyword: 'DDP',
    Protocol: 'Datagram Delivery Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Wesley_Craig]',
  },
  {
    Decimal: '38',
    Keyword: 'IDPR-CMTP',
    Protocol: 'IDPR Control Message Transport Proto',
    'IPv6 Extension Header': '',
    Reference: '[Martha_Steenstrup]',
  },
  {
    Decimal: '39',
    Keyword: 'TP++',
    Protocol: 'TP++ Transport Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Dirk_Fromhein]',
  },
  {
    Decimal: '40',
    Keyword: 'IL',
    Protocol: 'IL Transport Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Dave_Presotto]',
  },
  {
    Decimal: '41',
    Keyword: 'IPv6',
    Protocol: 'IPv6 encapsulation',
    'IPv6 Extension Header': '',
    Reference: '[RFC2473]',
  },
  {
    Decimal: '42',
    Keyword: 'SDRP',
    Protocol: 'Source Demand Routing Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Deborah_Estrin]',
  },
  {
    Decimal: '43',
    Keyword: 'IPv6-Route',
    Protocol: 'Routing Header for IPv6',
    'IPv6 Extension Header': 'Y',
    Reference: '[Steve_Deering]',
  },
  {
    Decimal: '44',
    Keyword: 'IPv6-Frag',
    Protocol: 'Fragment Header for IPv6',
    'IPv6 Extension Header': 'Y',
    Reference: '[Steve_Deering]',
  },
  {
    Decimal: '45',
    Keyword: 'IDRP',
    Protocol: 'Inter-Domain Routing Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Sue_Hares]',
  },
  {
    Decimal: '46',
    Keyword: 'RSVP',
    Protocol: 'Reservation Protocol',
    'IPv6 Extension Header': '',
    Reference: '[RFC2205][RFC3209][Bob_Braden]',
  },
  {
    Decimal: '47',
    Keyword: 'GRE',
    Protocol: 'Generic Routing Encapsulation',
    'IPv6 Extension Header': '',
    Reference: '[RFC2784][Tony_Li]',
  },
  {
    Decimal: '48',
    Keyword: 'DSR',
    Protocol: 'Dynamic Source Routing Protocol',
    'IPv6 Extension Header': '',
    Reference: '[RFC4728]',
  },
  {
    Decimal: '49',
    Keyword: 'BNA',
    Protocol: 'BNA',
    'IPv6 Extension Header': '',
    Reference: '[Gary Salamon]',
  },
  {
    Decimal: '50',
    Keyword: 'ESP',
    Protocol: 'Encap Security Payload',
    'IPv6 Extension Header': 'Y',
    Reference: '[RFC4303]',
  },
  {
    Decimal: '51',
    Keyword: 'AH',
    Protocol: 'Authentication Header',
    'IPv6 Extension Header': 'Y',
    Reference: '[RFC4302]',
  },
  {
    Decimal: '52',
    Keyword: 'I-NLSP',
    Protocol: 'Integrated Net Layer Security  TUBA',
    'IPv6 Extension Header': '',
    Reference: '[K_Robert_Glenn]',
  },
  {
    Decimal: '53',
    Keyword: 'SWIPE (deprecated)',
    Protocol: 'IP with Encryption',
    'IPv6 Extension Header': '',
    Reference: '[John_Ioannidis]',
  },
  {
    Decimal: '54',
    Keyword: 'NARP',
    Protocol: 'NBMA Address Resolution Protocol',
    'IPv6 Extension Header': '',
    Reference: '[RFC1735]',
  },
  {
    Decimal: '55',
    Keyword: 'MOBILE',
    Protocol: 'IP Mobility',
    'IPv6 Extension Header': '',
    Reference: '[Charlie_Perkins]',
  },
  {
    Decimal: '56',
    Keyword: 'TLSP',
    Protocol:
      'Transport Layer Security Protocol        \r\nusing Kryptonet key management',
    'IPv6 Extension Header': '',
    Reference: '[Christer_Oberg]',
  },
  {
    Decimal: '57',
    Keyword: 'SKIP',
    Protocol: 'SKIP',
    'IPv6 Extension Header': '',
    Reference: '[Tom_Markson]',
  },
  {
    Decimal: '58',
    Keyword: 'IPv6-ICMP',
    Protocol: 'ICMP for IPv6',
    'IPv6 Extension Header': '',
    Reference: '[RFC8200]',
  },
  {
    Decimal: '59',
    Keyword: 'IPv6-NoNxt',
    Protocol: 'No Next Header for IPv6',
    'IPv6 Extension Header': '',
    Reference: '[RFC8200]',
  },
  {
    Decimal: '60',
    Keyword: 'IPv6-Opts',
    Protocol: 'Destination Options for IPv6',
    'IPv6 Extension Header': 'Y',
    Reference: '[RFC8200]',
  },
  {
    Decimal: '61',
    Keyword: '',
    Protocol: 'any host internal protocol',
    'IPv6 Extension Header': '',
    Reference: '[Internet_Assigned_Numbers_Authority]',
  },
  {
    Decimal: '62',
    Keyword: 'CFTP',
    Protocol: 'CFTP',
    'IPv6 Extension Header': '',
    Reference:
      '[Forsdick, H., "CFTP", Network Message, Bolt Beranek and\r\nNewman, January 1982.][Harry_Forsdick]',
  },
  {
    Decimal: '63',
    Keyword: '',
    Protocol: 'any local network',
    'IPv6 Extension Header': '',
    Reference: '[Internet_Assigned_Numbers_Authority]',
  },
  {
    Decimal: '64',
    Keyword: 'SAT-EXPAK',
    Protocol: 'SATNET and Backroom EXPAK',
    'IPv6 Extension Header': '',
    Reference: '[Steven_Blumenthal]',
  },
  {
    Decimal: '65',
    Keyword: 'KRYPTOLAN',
    Protocol: 'Kryptolan',
    'IPv6 Extension Header': '',
    Reference: '[Paul Liu]',
  },
  {
    Decimal: '66',
    Keyword: 'RVD',
    Protocol: 'MIT Remote Virtual Disk Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Michael_Greenwald]',
  },
  {
    Decimal: '67',
    Keyword: 'IPPC',
    Protocol: 'Internet Pluribus Packet Core',
    'IPv6 Extension Header': '',
    Reference: '[Steven_Blumenthal]',
  },
  {
    Decimal: '68',
    Keyword: '',
    Protocol: 'any distributed file system',
    'IPv6 Extension Header': '',
    Reference: '[Internet_Assigned_Numbers_Authority]',
  },
  {
    Decimal: '69',
    Keyword: 'SAT-MON',
    Protocol: 'SATNET Monitoring',
    'IPv6 Extension Header': '',
    Reference: '[Steven_Blumenthal]',
  },
  {
    Decimal: '70',
    Keyword: 'VISA',
    Protocol: 'VISA Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Gene_Tsudik]',
  },
  {
    Decimal: '71',
    Keyword: 'IPCV',
    Protocol: 'Internet Packet Core Utility',
    'IPv6 Extension Header': '',
    Reference: '[Steven_Blumenthal]',
  },
  {
    Decimal: '72',
    Keyword: 'CPNX',
    Protocol: 'Computer Protocol Network Executive',
    'IPv6 Extension Header': '',
    Reference: '[David Mittnacht]',
  },
  {
    Decimal: '73',
    Keyword: 'CPHB',
    Protocol: 'Computer Protocol Heart Beat',
    'IPv6 Extension Header': '',
    Reference: '[David Mittnacht]',
  },
  {
    Decimal: '74',
    Keyword: 'WSN',
    Protocol: 'Wang Span Network',
    'IPv6 Extension Header': '',
    Reference: '[Victor Dafoulas]',
  },
  {
    Decimal: '75',
    Keyword: 'PVP',
    Protocol: 'Packet Video Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Steve_Casner]',
  },
  {
    Decimal: '76',
    Keyword: 'BR-SAT-MON',
    Protocol: 'Backroom SATNET Monitoring',
    'IPv6 Extension Header': '',
    Reference: '[Steven_Blumenthal]',
  },
  {
    Decimal: '77',
    Keyword: 'SUN-ND',
    Protocol: 'SUN ND PROTOCOL-Temporary',
    'IPv6 Extension Header': '',
    Reference: '[William_Melohn]',
  },
  {
    Decimal: '78',
    Keyword: 'WB-MON',
    Protocol: 'WIDEBAND Monitoring',
    'IPv6 Extension Header': '',
    Reference: '[Steven_Blumenthal]',
  },
  {
    Decimal: '79',
    Keyword: 'WB-EXPAK',
    Protocol: 'WIDEBAND EXPAK',
    'IPv6 Extension Header': '',
    Reference: '[Steven_Blumenthal]',
  },
  {
    Decimal: '80',
    Keyword: 'ISO-IP',
    Protocol: 'ISO Internet Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Marshall_T_Rose]',
  },
  {
    Decimal: '81',
    Keyword: 'VMTP',
    Protocol: 'VMTP',
    'IPv6 Extension Header': '',
    Reference: '[Dave_Cheriton]',
  },
  {
    Decimal: '82',
    Keyword: 'SECURE-VMTP',
    Protocol: 'SECURE-VMTP',
    'IPv6 Extension Header': '',
    Reference: '[Dave_Cheriton]',
  },
  {
    Decimal: '83',
    Keyword: 'VINES',
    Protocol: 'VINES',
    'IPv6 Extension Header': '',
    Reference: '[Brian Horn]',
  },
  {
    Decimal: '84',
    Keyword: 'TTP',
    Protocol: 'Transaction Transport Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Jim_Stevens]',
  },
  {
    Decimal: '84',
    Keyword: 'IPTM',
    Protocol: 'Internet Protocol Traffic Manager',
    'IPv6 Extension Header': '',
    Reference: '[Jim_Stevens]',
  },
  {
    Decimal: '85',
    Keyword: 'NSFNET-IGP',
    Protocol: 'NSFNET-IGP',
    'IPv6 Extension Header': '',
    Reference: '[Hans_Werner_Braun]',
  },
  {
    Decimal: '86',
    Keyword: 'DGP',
    Protocol: 'Dissimilar Gateway Protocol',
    'IPv6 Extension Header': '',
    Reference:
      '[M/A-COM Government Systems, "Dissimilar Gateway Protocol\r\nSpecification, Draft Version", Contract no. CS901145,\r\nNovember 16, 1987.][Mike_Little]',
  },
  {
    Decimal: '87',
    Keyword: 'TCF',
    Protocol: 'TCF',
    'IPv6 Extension Header': '',
    Reference: '[Guillermo_A_Loyola]',
  },
  {
    Decimal: '88',
    Keyword: 'EIGRP',
    Protocol: 'EIGRP',
    'IPv6 Extension Header': '',
    Reference: '[RFC7868]',
  },
  {
    Decimal: '89',
    Keyword: 'OSPFIGP',
    Protocol: 'OSPFIGP',
    'IPv6 Extension Header': '',
    Reference: '[RFC1583][RFC2328][RFC5340][John_Moy]',
  },
  {
    Decimal: '90',
    Keyword: 'Sprite-RPC',
    Protocol: 'Sprite RPC Protocol',
    'IPv6 Extension Header': '',
    Reference:
      '[Welch, B., "The Sprite Remote Procedure Call System",\r\nTechnical Report, UCB/Computer Science Dept., 86/302,\r\nUniversity of California at Berkeley, June 1986.][Bruce Willins]',
  },
  {
    Decimal: '91',
    Keyword: 'LARP',
    Protocol: 'Locus Address Resolution Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Brian Horn]',
  },
  {
    Decimal: '92',
    Keyword: 'MTP',
    Protocol: 'Multicast Transport Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Susie_Armstrong]',
  },
  {
    Decimal: '93',
    Keyword: 'AX.25',
    Protocol: 'AX.25 Frames',
    'IPv6 Extension Header': '',
    Reference: '[Brian_Kantor]',
  },
  {
    Decimal: '94',
    Keyword: 'IPIP',
    Protocol: 'IP-within-IP Encapsulation Protocol',
    'IPv6 Extension Header': '',
    Reference: '[John_Ioannidis]',
  },
  {
    Decimal: '95',
    Keyword: 'MICP (deprecated)',
    Protocol: 'Mobile Internetworking Control Pro.',
    'IPv6 Extension Header': '',
    Reference: '[John_Ioannidis]',
  },
  {
    Decimal: '96',
    Keyword: 'SCC-SP',
    Protocol: 'Semaphore Communications Sec. Pro.',
    'IPv6 Extension Header': '',
    Reference: '[Howard_Hart]',
  },
  {
    Decimal: '97',
    Keyword: 'ETHERIP',
    Protocol: 'Ethernet-within-IP Encapsulation',
    'IPv6 Extension Header': '',
    Reference: '[RFC3378]',
  },
  {
    Decimal: '98',
    Keyword: 'ENCAP',
    Protocol: 'Encapsulation Header',
    'IPv6 Extension Header': '',
    Reference: '[RFC1241][Robert_Woodburn]',
  },
  {
    Decimal: '99',
    Keyword: '',
    Protocol: 'any private encryption scheme',
    'IPv6 Extension Header': '',
    Reference: '[Internet_Assigned_Numbers_Authority]',
  },
  {
    Decimal: '100',
    Keyword: 'GMTP',
    Protocol: 'GMTP',
    'IPv6 Extension Header': '',
    Reference: '[[RXB5]]',
  },
  {
    Decimal: '101',
    Keyword: 'IFMP',
    Protocol: 'Ipsilon Flow Management Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Bob_Hinden][November 1995, 1997.]',
  },
  {
    Decimal: '102',
    Keyword: 'PNNI',
    Protocol: 'PNNI over IP',
    'IPv6 Extension Header': '',
    Reference: '[Ross_Callon]',
  },
  {
    Decimal: '103',
    Keyword: 'PIM',
    Protocol: 'Protocol Independent Multicast',
    'IPv6 Extension Header': '',
    Reference: '[RFC7761][Dino_Farinacci]',
  },
  {
    Decimal: '104',
    Keyword: 'ARIS',
    Protocol: 'ARIS',
    'IPv6 Extension Header': '',
    Reference: '[Nancy_Feldman]',
  },
  {
    Decimal: '105',
    Keyword: 'SCPS',
    Protocol: 'SCPS',
    'IPv6 Extension Header': '',
    Reference: '[Robert_Durst]',
  },
  {
    Decimal: '106',
    Keyword: 'QNX',
    Protocol: 'QNX',
    'IPv6 Extension Header': '',
    Reference: '[Michael_Hunter]',
  },
  {
    Decimal: '107',
    Keyword: 'A/N',
    Protocol: 'Active Networks',
    'IPv6 Extension Header': '',
    Reference: '[Bob_Braden]',
  },
  {
    Decimal: '108',
    Keyword: 'IPComp',
    Protocol: 'IP Payload Compression Protocol',
    'IPv6 Extension Header': '',
    Reference: '[RFC2393]',
  },
  {
    Decimal: '109',
    Keyword: 'SNP',
    Protocol: 'Sitara Networks Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Manickam_R_Sridhar]',
  },
  {
    Decimal: '110',
    Keyword: 'Compaq-Peer',
    Protocol: 'Compaq Peer Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Victor_Volpe]',
  },
  {
    Decimal: '111',
    Keyword: 'IPX-in-IP',
    Protocol: 'IPX in IP',
    'IPv6 Extension Header': '',
    Reference: '[CJ_Lee]',
  },
  {
    Decimal: '112',
    Keyword: 'VRRP',
    Protocol: 'Virtual Router Redundancy Protocol',
    'IPv6 Extension Header': '',
    Reference: '[RFC5798]',
  },
  {
    Decimal: '113',
    Keyword: 'PGM',
    Protocol: 'PGM Reliable Transport Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Tony_Speakman]',
  },
  {
    Decimal: '114',
    Keyword: '',
    Protocol: 'any 0-hop protocol',
    'IPv6 Extension Header': '',
    Reference: '[Internet_Assigned_Numbers_Authority]',
  },
  {
    Decimal: '115',
    Keyword: 'L2TP',
    Protocol: 'Layer Two Tunneling Protocol',
    'IPv6 Extension Header': '',
    Reference: '[RFC3931][Bernard_Aboba]',
  },
  {
    Decimal: '116',
    Keyword: 'DDX',
    Protocol: 'D-II Data Exchange (DDX)',
    'IPv6 Extension Header': '',
    Reference: '[John_Worley]',
  },
  {
    Decimal: '117',
    Keyword: 'IATP',
    Protocol: 'Interactive Agent Transfer Protocol',
    'IPv6 Extension Header': '',
    Reference: '[John_Murphy]',
  },
  {
    Decimal: '118',
    Keyword: 'STP',
    Protocol: 'Schedule Transfer Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Jean_Michel_Pittet]',
  },
  {
    Decimal: '119',
    Keyword: 'SRP',
    Protocol: 'SpectraLink Radio Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Mark_Hamilton]',
  },
  {
    Decimal: '120',
    Keyword: 'UTI',
    Protocol: 'UTI',
    'IPv6 Extension Header': '',
    Reference: '[Peter_Lothberg]',
  },
  {
    Decimal: '121',
    Keyword: 'SMP',
    Protocol: 'Simple Message Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Leif_Ekblad]',
  },
  {
    Decimal: '122',
    Keyword: 'SM (deprecated)',
    Protocol: 'Simple Multicast Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Jon_Crowcroft][draft-perlman-simple-multicast]',
  },
  {
    Decimal: '123',
    Keyword: 'PTP',
    Protocol: 'Performance Transparency Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Michael_Welzl]',
  },
  {
    Decimal: '124',
    Keyword: 'ISIS over IPv4',
    Protocol: '',
    'IPv6 Extension Header': '',
    Reference: '[Tony_Przygienda]',
  },
  {
    Decimal: '125',
    Keyword: 'FIRE',
    Protocol: '',
    'IPv6 Extension Header': '',
    Reference: '[Criag_Partridge]',
  },
  {
    Decimal: '126',
    Keyword: 'CRTP',
    Protocol: 'Combat Radio Transport Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Robert_Sautter]',
  },
  {
    Decimal: '127',
    Keyword: 'CRUDP',
    Protocol: 'Combat Radio User Datagram',
    'IPv6 Extension Header': '',
    Reference: '[Robert_Sautter]',
  },
  {
    Decimal: '128',
    Keyword: 'SSCOPMCE',
    Protocol: '',
    'IPv6 Extension Header': '',
    Reference: '[Kurt_Waber]',
  },
  {
    Decimal: '129',
    Keyword: 'IPLT',
    Protocol: '',
    'IPv6 Extension Header': '',
    Reference: '[[Hollbach]]',
  },
  {
    Decimal: '130',
    Keyword: 'SPS',
    Protocol: 'Secure Packet Shield',
    'IPv6 Extension Header': '',
    Reference: '[Bill_McIntosh]',
  },
  {
    Decimal: '131',
    Keyword: 'PIPE',
    Protocol: 'Private IP Encapsulation within IP',
    'IPv6 Extension Header': '',
    Reference: '[Bernhard_Petri]',
  },
  {
    Decimal: '132',
    Keyword: 'SCTP',
    Protocol: 'Stream Control Transmission Protocol',
    'IPv6 Extension Header': '',
    Reference: '[Randall_R_Stewart]',
  },
  {
    Decimal: '133',
    Keyword: 'FC',
    Protocol: 'Fibre Channel',
    'IPv6 Extension Header': '',
    Reference: '[Murali_Rajagopal][RFC6172]',
  },
  {
    Decimal: '134',
    Keyword: 'RSVP-E2E-IGNORE',
    Protocol: '',
    'IPv6 Extension Header': '',
    Reference: '[RFC3175]',
  },
  {
    Decimal: '135',
    Keyword: 'Mobility Header',
    Protocol: '',
    'IPv6 Extension Header': 'Y',
    Reference: '[RFC6275]',
  },
  {
    Decimal: '136',
    Keyword: 'UDPLite',
    Protocol: '',
    'IPv6 Extension Header': '',
    Reference: '[RFC3828]',
  },
  {
    Decimal: '137',
    Keyword: 'MPLS-in-IP',
    Protocol: '',
    'IPv6 Extension Header': '',
    Reference: '[RFC4023]',
  },
  {
    Decimal: '138',
    Keyword: 'manet',
    Protocol: 'MANET Protocols',
    'IPv6 Extension Header': '',
    Reference: '[RFC5498]',
  },
  {
    Decimal: '139',
    Keyword: 'HIP',
    Protocol: 'Host Identity Protocol',
    'IPv6 Extension Header': 'Y',
    Reference: '[RFC7401]',
  },
  {
    Decimal: '140',
    Keyword: 'Shim6',
    Protocol: 'Shim6 Protocol',
    'IPv6 Extension Header': 'Y',
    Reference: '[RFC5533]',
  },
  {
    Decimal: '141',
    Keyword: 'WESP',
    Protocol: 'Wrapped Encapsulating Security Payload',
    'IPv6 Extension Header': '',
    Reference: '[RFC5840]',
  },
  {
    Decimal: '142',
    Keyword: 'ROHC',
    Protocol: 'Robust Header Compression',
    'IPv6 Extension Header': '',
    Reference: '[RFC5858]',
  },
  {
    Decimal: '143',
    Keyword: 'Ethernet',
    Protocol:
      'Ethernet (TEMPORARY - registered 2020-01-31, expires 2021-01-31)',
    'IPv6 Extension Header': '',
    Reference: '[draft-ietf-spring-srv6-network-programming]',
  },
  {
    Decimal: '144-252',
    Keyword: '',
    Protocol: 'Unassigned',
    'IPv6 Extension Header': '',
    Reference: '[Internet_Assigned_Numbers_Authority]',
  },
  {
    Decimal: '253',
    Keyword: '',
    Protocol: 'Use for experimentation and testing',
    'IPv6 Extension Header': 'Y',
    Reference: '[RFC3692]',
  },
  {
    Decimal: '254',
    Keyword: '',
    Protocol: 'Use for experimentation and testing',
    'IPv6 Extension Header': 'Y',
    Reference: '[RFC3692]',
  },
  {
    Decimal: '255',
    Keyword: 'Reserved',
    Protocol: '',
    'IPv6 Extension Header': '',
    Reference: '[Internet_Assigned_Numbers_Authority]',
  },
];
