import {RoutingRuleSpec} from '../../graph';

import {AzurePublicIP, AzureVirtualNetwork} from './azure_types';
import {GraphServices} from './graph_services';

///////////////////////////////////////////////////////////////////////////////
//
// convertResourceGraph() is responsible for
//   1. Creating the `Internet` node with routes to all public ips.
//   2. Materializing root nodes for VNets, NICs, and possibly compute pools.
//   3. Defining the `Internet` service tag, which is referenced by routing
//      and filtering rules in VNets and NSGs.
//
///////////////////////////////////////////////////////////////////////////////
export function convertResourceGraph(services: GraphServices) {
  // The Azure resource graph is considered to be a forest of AnyAzureObjects,
  // some of which are AzureVirtualNetworks.

  // TODO: Allocate internetNodeKey to avoid possible collisions
  const internetKey = services.getInternetKey();
  const gatewayKeyPrefix = 'AzureGateway';
  const gatewayInboundKey = services.nodes.createKeyVariant(
    gatewayKeyPrefix,
    'inbound'
  );
  const gatewayOutboundKey = services.nodes.createKeyVariant(
    gatewayKeyPrefix,
    'outbound'
  );

  //
  // Materialize each public ip.
  //

  const internetRoutes: RoutingRuleSpec[] = [];
  const gatewayOutboundRoutes: RoutingRuleSpec[] = [];
  for (const ipSpec of services.index.withType(AzurePublicIP)) {
    const {inbound, outbound} = services.convert.publicIp(
      services,
      ipSpec,
      gatewayInboundKey,
      internetKey
    );

    for (const route of inbound) {
      internetRoutes.push(route);
    }
    for (const route of outbound) {
      gatewayOutboundRoutes.push(route);
    }
  }

  // Create internet node
  services.nodes.add({
    key: internetKey,
    endpoint: true,
    routes: internetRoutes,
  });

  //
  // Create outbound gateway node
  //
  services.nodes.add({
    key: gatewayOutboundKey,
    routes: gatewayOutboundRoutes,
  });

  //
  // Create inbound gateway node
  //

  // Materialize each virtual network, while saving its NodeKey for later use.
  // Create routes from internet to each virtual network.
  const vNetNodeKeys: string[] = [];
  const gatewayInboundRoutes: RoutingRuleSpec[] = [];
  for (const vnet of services.index.withType(AzureVirtualNetwork)) {
    const route = services.convert.vnet(services, vnet, gatewayOutboundKey);
    vNetNodeKeys.push(route.destination);
    gatewayInboundRoutes.push(route);
  }

  services.nodes.add({
    key: gatewayInboundKey,
    routes: gatewayInboundRoutes,
  });

  // Define a service tag for `Internet`, which is referenced in router rules
  // generated by converters like vNetConverter(). Azure defines `Internet` as
  // any ip addresses not in the ranges of the VNets.
  // See https://docs.microsoft.com/en-us/azure/virtual-network/service-tags-overview
  const sourceIp = `except ${vNetNodeKeys.join(',')}`;
  services.symbols.defineServiceTag(internetKey, sourceIp);
}
